config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'debates#index'

  resources :debates do
    member do
      post :vote
    end

    resources :comments, only: :create, shallow: true do
      member do
        post :vote
      end
    end

  end

  resource :account, controller: "account", only: [:show, :update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set scope: [:commentable_id, :commentable_type]
  acts_as_votable

  validates :body, presence: true
  validates :user, presence: true

  belongs_to :commentable, polymorphic: true
  belongs_to :user

  def self.build(commentable, user, body)
    new commentable: commentable,
        user_id:     user.id,
        body:        body
  end

  def self.find_parent(params)
    params[:commentable_type].constantize.find(params[:commentable_id])
  end

  def debate
    commentable if commentable.class == Debate
  end

  def author
    user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_debate, :set_parent, only: :create
  respond_to :html, :js

  def create
    @comment = Comment.build(@debate, current_user, params[:comment][:body])
    @comment.save!
    @comment.move_to_child_of(@parent) if reply?

    Mailer.comment(@comment).deliver_now if email_on_debate_comment?
    Mailer.reply(@comment).deliver_now if email_on_comment_reply?

    respond_with @comment
  end

  def vote
    @comment = Comment.find(params[:id])
    @comment.vote_by(voter: current_user, vote: params[:value])
    respond_with @comment
  end

  private
    def comment_params
      params.require(:comments).permit(:commentable_type, :commentable_id, :body)
    end

    def set_debate
      @debate = Debate.find(params[:debate_id])
    end

    def set_parent
      @parent = Comment.find_parent(params[:comment])
    end

    def reply?
      @parent.class == Comment
    end

    def email_on_debate_comment?
      @comment.debate.author.email_on_debate_comment?
    end

    def email_on_comment_reply?
      reply? && @parent.author.email_on_comment_reply?
    end
end

app/helpers/comments_helper.rb
module CommentsHelper

  def comment_link_text(parent)
    parent.class == Debate ? t("comments_helper.comment_link") : t("comments_helper.reply_link")
  end

  def comment_button_text(parent)
    parent.class == Debate ? t("comments_helper.comment_button") : t("comments_helper.reply_button")
  end

end

app/views/comments/_comment.html.erb
<div class="row">
	<div id="comment-<%= comment.id %>" class="small-12 column comment">

		<%= image_tag('user_default_2.jpg', class: 'user-photo left', size: '32x32') %>

	 	<div class="comment-body">
	 		<span class="comment-info">
	 			<%= comment.user.name %>&nbsp;&bullet;&nbsp;<%= time_ago_in_words(comment.created_at) %>
	 		</span>
  		<p><%= comment.body %></p>

  		<span id="<%= dom_id(comment) %>_votes">
  		  <%= render 'comments/votes', comment: comment %>
  		</span>

  		<% if user_signed_in? %>
  		<p class="reply"><%= render 'comments/form', {parent: comment, toggeable: true} %></p>
  		<% end %>
	  </div>

  	<div class="comment-children">
    	<%= render comment.children %>
  	</div>
	</div>
</div>

app/views/comments/_form.html.erb
<%= link_to(comment_link_text(parent), "", class: "js-add-comment-link", data: {'id': dom_id(parent)}) if toggeable %>

<div id="js-comment-form-<%= dom_id(parent) %>" <%= "style='display:none'".html_safe if toggeable %>>
  <%= form_for [@debate, Comment.new], remote: true do |f| %>
    <%= f.text_area :body %>
    <%= f.hidden_field :commentable_type, value: parent.class %>
    <%= f.hidden_field :commentable_id, value: parent.id %>

    <%= f.submit comment_button_text(parent), class: "button radius small" %>
  <% end %>
</div>

app/views/comments/_votes.html.erb
<span class="in_favor">
  <%= link_to "up", vote_comment_path(comment, value: 'yes'),
    method: "post", remote: true %>
  <%= comment.get_likes.size %>
</span>

<span class="against">
  <%= link_to "down", vote_comment_path(comment, value: 'no'),
      method: "post", remote: true %>
  <%= comment.get_dislikes.size %>
</span>

app/views/comments/create.js.erb
var parent_id = '<%= dom_id(@parent) %>';
App.Comments.reset_and_hide_form(parent_id);
App.Comments.add_response(parent_id, "<%= j(render @comment) %>");

app/views/comments/vote.js.erb
$("#<%= dom_id(@comment) %>_votes").html('<%= j render("comments/votes", comment: @comment) %>');