config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'debates#index'

  resources :debates do
    member do
      post :vote
    end

    resources :comments, only: :create, shallow: true do
      member do
        post :vote
      end
    end

  end

  resource :account, controller: "account", only: [:show, :update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/debate.rb
require 'numeric'
class Debate < ActiveRecord::Base

  TITLE_LENGTH = Debate.columns.find{|c| c.name == 'title'}.limit

  acts_as_votable
  acts_as_commentable
  acts_as_taggable

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :title, presence: true
  validates :description, presence: true
  validates :author, presence: true

  validates :terms_of_service, acceptance: { allow_nil: false }, on: :create

  before_validation :sanitize_description
  before_validation :sanitize_tag_list

  def likes
    get_likes.size
  end

  def dislikes
    get_dislikes.size
  end

  def total_votes
    votes_for.size
  end

  def editable?
    total_votes == 0
  end

  def editable_by?(user)
    editable? && author == user
  end

  def description
    super.try :html_safe
  end

  protected

  def sanitize_description
    self.description = WYSIWYGSanitizer.new.sanitize(description)
  end

  def sanitize_tag_list
    self.tag_list  = TagSanitizer.new.sanitize_tag_list(self.tag_list)
  end

end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
  include RecaptchaHelper
  before_action :set_debate, only: [:show, :edit, :update, :vote]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :validate_ownership, only: [:edit, :update]

  def index
    if params[:tag]
      @debates = Debate.tagged_with(params[:tag]).order("created_at DESC")
      set_voted_values @debates.map(&:id)
    else
      @debates = Debate.all.order("created_at DESC")
      set_voted_values @debates.map(&:id)
      @featured_debates = @debates.to_a.shift(3)
    end
  end

  def show
    set_voted_values [@debate.id]
  end

  def new
    @debate = Debate.new
  end

  def edit
  end

  def create
    @debate = Debate.new(debate_params)
    @debate.author = current_user
    if verify_captcha?(@debate) and @debate.save
      redirect_to @debate, notice: t('flash.actions.create.notice', resource_name: 'Debate')
    else
      render :new
    end
  end

  def update
    @debate.update(debate_params)
    respond_with @debate
  end

  def vote
    @debate.vote_by(voter: current_user, vote: params[:value])
    set_voted_values [@debate.id]
  end


  private
    def set_debate
      @debate = Debate.find(params[:id])
    end

    def debate_params
      params.require(:debate).permit(:title, :description, :tag_list, :terms_of_service)
    end

    def validate_ownership
      raise ActiveRecord::RecordNotFound unless @debate.editable_by?(current_user)
    end

    def set_voted_values(debates_ids)
      @voted_values = current_user ? current_user.votes_on_debates(debates_ids) : {}
    end
end

app/views/debates/_debate.html.erb
<div id="debate-<%= debate.id %>" class="debate">
  <div class="panel">
    <div class="row">

      <div class="small-12 medium-9 column">
        <div class="debate-content">
          <span class="label left"><%= t("debates.debate.debate") %></span>
          <i class="icon-comment-quotes"></i>
          <h3><%= link_to debate.title, debate %></h3>
          <p class="debate-info">
            <i class="icon-chat-bubble-two"></i>&nbsp;
            <%= pluralize(debate.comment_threads.count,
                t("debates.debate.comment"), t("debates.debate.comments")) %>
          </p>
          <div class="debate-description">
            <%= link_to debate.description, debate %>
            <div class="truncate"></div>
          </div>
          <%= render "shared/tags", debate: debate %>
        </div>
      </div>

      <div id="<%= dom_id(debate) %>_votes" class="small-12 medium-3 column text-center">
          <%= render 'debates/votes', debate: debate %>
      </div>

    </div>
  </div>
</div>

app/views/debates/_featured_debate.html.erb
<div class="small-12 medium-4 column">
  <div id="<%= dom_id featured_debate %>" class="debate-featured">
    <div class="panel">

      <div class="debate-content">
        <span class="label left"><%= t("debates.debate.debate") %></span>
        <i class="icon-comment-quotes right"></i>
        <h3><%= link_to featured_debate.title, featured_debate %></h3>
        <p class="debate-info">
          <i class="icon-chat-bubble-two"></i>&nbsp;
          <%= pluralize(featured_debate.comment_threads.count,
              t("debates.show.comment"), t("debates.show.comments")) %>
        </p>
        <div class="debate-description">
          <%= link_to featured_debate.description, featured_debate %>
          <div class="truncate"></div>
        </div>
        <%= render "shared/tags", debate: featured_debate %>
      </div>

      <div class="row">
        <div id="<%= dom_id(featured_debate) %>_votes" class="small-12 column">
          <%= render 'debates/votes', debate: featured_debate %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/debates/_form.html.erb
<%= form_for(@debate) do |f| %>
  <% if @debate.errors.any? %>
    <div id="error_explanation" class="alert-box alert radius">
      <p><strong><%= pluralize(@debate.errors.count, t("debates.form.error"), t("debates.form.errors")) %> <%= t("debates.form.not_saved") %></strong></p>
      <ul>
          <% @debate.errors.full_messages.each do |message| %>
              <li><%= message %></li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="small-12 column">
      <%= f.label :title, t("debates.form.debate_title") %>
      <span class="note"><%= t("debates.form.title_instructions") %></span>
      <%= f.text_field :title, maxlength: Debate::TITLE_LENGTH %>
    </div>

    <div class="ckeditor small-12 column">
      <%= f.label :description, t("debates.form.debate_text") %>
      <span class="note"><%= t("debates.form.text_instructions") %></span>
      <%= f.cktext_area :description, ckeditor: { language: I18n.locale } %>
    </div>

    <div class="small-12 column">
      <%= f.label :tag_list, t("debates.form.tags_label") %>
      <span class="note"><%= t("debates.form.tags_instructions") %></span>
      <%= f.text_field :tag_list, value: @debate.tag_list.to_s %>
    </div>

    <div class="small-12 column">
      <% if @debate.new_record? %>
        <%= f.check_box :terms_of_service %>
        <span class="checkbox"><%= t("debates.form.accept_terms") %></span>
      <% end %>
    </div>

    <div class="small-12 column">
      <%= render 'shared/captcha', resource: @debate %>
    </div>

    <div class="actions small-12 column">
      <%= f.submit(class: "button radius") %>
    </div>
  </div>
<% end %>

app/views/debates/_votes.html.erb
<% voted_classes = css_classes_for_debate_vote(@voted_values, debate) %>
<div class="votes">
  <div class="in-favor inline-block">
    <%= link_to vote_debate_path(debate, value: 'yes'),
        class: "like #{voted_classes[:in_favor]}", title: t('votes.agree'), method: "post", remote: true do %>
      <i class="icon-like"></i>
      <span><%= percentage('likes', debate) %></span>
    <% end %>
  </div>

  <span class="divider"></span>

  <div class="against inline-block">
    <%= link_to vote_debate_path(debate, value: 'no'), class: "unlike #{voted_classes[:against]}", title: t('votes.disagree'), method: "post", remote: true do %>
      <i class="icon-unlike"></i>
      <span><%= percentage('dislikes', debate) %></span>
    <% end %>
  </div>

  <span class="total-votes">
    <%= pluralize(debate.total_votes, t("debates.debate.vote"), t("debates.debate.votes")) %>
  </span>
</div>

app/views/debates/edit.html.erb
<h1><%= t("debates.edit.editing") %></h1>

<%= render 'form' %>

<%= link_to t("debates.edit.show_link"), @debate %> |
<%= link_to t("debates.edit.back_link"), debates_path %>

app/views/debates/index.html.erb
<section role="main">
  <div id="featured-debates" class="row">
    <%= render partial: "featured_debate", collection: @featured_debates %>
  </div>
  <div class="row">
    <div id="debates" class="small-12 medium-9 column debates-list">
      <%= render @debates %>
    </div>
    <div class="small-12 medium-3 column">
      <aside role="complementary">
        <%= link_to t("debates.index.create_debate"), new_debate_path, class: 'button radius expand' %>
        <%= render "shared/tag_cloud" %>
      </aside>
    </div>
  </div>
</section>

app/views/debates/new.html.erb
<div class="debate-new row">

  <div class="small-12 medium-9 column">
    <%= link_to debates_path, class: "left back" do %>
      <i class="icon-angle-left left"></i>
      <%= t("debates.new.back_link") %>
    <% end %>
    <h1><%= t("debates.new.publish_new") %></h1>
    <%= render "form" %>
  </div>

  <div class="small-12 medium-3 column">
    <i class="icon-comment-quotes right"></i>
    <h2><%= t("debates.new.recommendations_title") %></h2>
    <ul class="recommendations">
      <li><%= t("debates.new.recommendation_one") %></li>
      <li><%= t("debates.new.recommendation_two") %></li>
      <li><%= t("debates.new.recommendation_three") %></li>
    </ul>
  </div>
</div>

app/views/debates/show.html.erb
<section class="debate-show">
  <div id="debate-<%= @debate.id %>" class="row">
    <div class="small-12 medium-9 column">
      <i class="icon-angle-left left"></i>&nbsp;<%= link_to t("debates.show.back_link"), debates_path, class: 'left back' %>
      <div class="debate-info">
        <%= image_tag('user_default.jpg', class: 'author-photo', size: '32x32') %>
        <span class="author"><%= @debate.author.name %></span><span class="bullet">&nbsp;&bullet;&nbsp;</span> <%= l @debate.created_at.to_date %> <span class="bullet">&nbsp;&bullet;&nbsp;</span><i class="icon-chat-bubble-two"></i>&nbsp;<%= pluralize(@debate.comment_threads.count, t("debates.show.comment"), t("debates.show.comments")) %>
      </div>
      <h1><%= @debate.title %></h1>
      <%= @debate.description %>
      <p><%= render 'shared/tags', debate: @debate %></p>
    </div>

    <div id="<%= dom_id(@debate) %>_votes" class="small-12 medium-3 column">
      <h3><%= t("votes.supports") %></h3>
      <div class="text-center">
        <%= render 'debates/votes', debate: @debate %>
        <% if user_signed_in? %>
          <%= link_to t("debates.show.leave_comment"), "#comments", class: "leave-comment" %>
        <% else %>
          <%= link_to t("debates.show.login_to_comment"), new_user_session_path, class: "leave-comment" %>
        <% end %>
      </div>
    </div>

  </div>
</section>

<section class="row-full comments">
  <div class="row">
    <div id="comments" class="small-12 column">
      <h2><%= t("debates.show.comments") %></h2>
      <% if user_signed_in? %>
        <div>
          <%= t("debates.show.leave_comment") %>
          <%= render 'comments/form', {parent: @debate, toggeable: false} %>
        </div>
      <% end %>
      <%= render @debate.root_comments %>
    </div>
    <% if current_user && @debate.editable_by?(current_user) %>
      <%= link_to t("debates.show.edit_debate_link"), edit_debate_path(@debate), :class => 'button radius right' %>
    <% end %>
  </div>
</section>

app/views/debates/vote.js.erb
$("#<%= dom_id(@debate) %>_votes").html('<%= j render("debates/votes", debate: @debate) %>');