config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  root 'debates#index'

  resources :debates do
    member do
      post :vote
    end

    resources :comments, only: :create, shallow: true do
      member do
        post :vote
      end
    end

  end

  resource :account, controller: "account", only: [:show, :update]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/views/layouts/_footer.html.erb
<div style="background: #0077b9; width: 100%;">
	<%= image_tag('footer.jpg', style: 'width: 100%; max-width: 1170px;') %>
</div>

app/views/layouts/_header.html.erb
<header class="<%= header_css %>">
	<section class="top-links">
		<div class="row">
			<div class="small-12 column">
				<div class="right">
					<a href="#"><%= t("layouts.header.external_link_transparency") %></a> | <a href="#"><%= t("layouts.header.external_link_opendata") %></a>
          |
          <span id="locale-switcher">
            [
              <% available_locales_to_switch.each do |locale| %>
                <%= link_to(locale, params.merge(locale: locale), id: "locale-link-#{locale}") %>
              <% end %>
            ]
          </span>
				</div>
			</div>
		</div>
	</section>

	<div class="contain-to-grid">
		<nav class="top-bar" data-topbar role="navigation">
			<ul class="title-area">
				<li class="name">
					<%= link_to root_path do %>
						<%= image_tag('header_logo_madrid.png', class: 'left', size: '96x96') %>
						<%= t("layouts.header.open_gov", open: "<strong>#{t('layouts.header.open')}</strong>").html_safe %> | <span><%= t("layouts.header.participation") %></span>
					<% end %>
				</li>
				<li class="toggle-topbar menu-icon"><a href="#"><span><%= t("layouts.header.menu") %></span></a></li>
			</ul>

			<section class="top-bar-section">
				<%= render 'devise/menu/login_items' %>

				<% if user_signed_in? %>
				<ul class="right">
					<li><%= link_to(t("layouts.header.my_account_link"), account_path) %></li>
				</ul>
				<% end %>
			</section>
		</nav>
	</div>

	<% if home_page? %>
		<div class="row">
			<div class="small-12 column text-center">
				<h1><%= t("layouts.header.open_city") %></h1>
				<h2><%= t("layouts.header.open_city_slogan") %></h2>
				<%= link_to t("layouts.header.create_debate"), new_debate_path, class: 'button radius' %>
			</div>
		</div>
	<% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title><%= content_for?(:title) ? yield(:title) : "Participación" %></title>
        <%= stylesheet_link_tag    "application" %>
        <%= javascript_include_tag "vendor/modernizr" %>
        <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <script src="https://www.google.com/recaptcha/api.js?hl=<%= I18n.locale %>"></script>
    </head>
  <body>

    <%= render 'layouts/header' %>

    <% if notice %>
        <p class="alert-box success"><%= notice %></p>
    <% end %>

    <% if alert %>
        <p class="alert-box"><%= alert %></p>
    <% end %>

    <%= yield %>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Participación" %></title>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <script src="https://www.google.com/recaptcha/api.js?hl=<%= I18n.locale %>"></script>
  </head>

  <body class="auth-page">

    <% if notice %>
        <p class="alert-box success"><%= notice %></p>
    <% end %>

    <% if alert %>
        <p class="alert-box"><%= alert %></p>
    <% end %>

    <div class="row">
      <div class="small-12 medium-8 large-5 column small-centered">
        <h1>
          <%= link_to root_path do %>
            <%= image_tag('logo_madrid_white.png', class: 'left', size: '96x96') %>
            <%= t("layouts.header.open_gov", open: "<strong>#{t('layouts.header.open')}</strong>").html_safe %> | <span><%= t("layouts.header.participation") %></span>
          <% end %>
        </h1>
      </div>
    </div>

    <%= yield %>

  </body>
</html>